# Generated by Django 5.2.4 on 2025-08-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(max_length=50)),
                ('video_file', models.FileField(upload_to='videos')),
                ('video_480p', models.FileField(blank=True, null=True, upload_to='videos/480p/')),
                ('video_720p', models.FileField(blank=True, null=True, upload_to='videos/720p/')),
                ('video_1080p', models.FileField(blank=True, null=True, upload_to='videos/1080p/')),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
