# Generated by Django 5.2.4 on 2025-08-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0004_remove_video_thumbnail_url_video_cover_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='video',
            name='thumbnail_image',
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
